### ISSUE TITLE
Time failure

### ISSUE THREAD

**Issue by xeeek** [hermansimensen/carnifex-TAS#1]
When hitting an inclined surface (bhop_fps_max 16 stage as an example), if the time was slowed down, it returns to normal. But the timer continues to run in slow motion.

**Comment by hermansimensen** [comment]
I can't replicate this issue. Could you give more information?

**Comment by hermansimensen** [comment]
I've been able to recreate this once, but it seems to be quite random.

**Comment by hermansimensen** [comment]
Closing since its random and not replicable
